apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod-with-sidecar
spec:
  containers:
    - name: main-container
      image: busybox:latest
      volumeMounts:
        - mountPath: /var/i-am-empty-dir-volume
          name: empty-dir-volume
    - name: sidecar-container
      image: # add your image
      volumeMounts:
        - mountPath: /var/i-am-empty-dir-volume
          name: empty-dir-volume
  volumes:
    - name: empty-dir-volume
      emptyDir: {} # initialize an empty dir volume
